stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm ci

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y lftp
    - lftp -e "set ftp:ssl-allow no; mirror -R build/ /chemin/vers/distant; bye" -u "$FTP_USERNAME","$FTP_PASSWORD" ftp://$FTP_HOST
  only:
    - main
